### ISSUE TITLE
erroneous line that should be removed 

### ISSUE THREAD

**Issue by Kadwen01** [chrisrabe/bitburner-automation#11]
https://github.com/chrisrabe/bitburner-automation/blob/3ef047268eee125b501c113c868530e9e24fb1d6/_stable/aps-lite.js#L41

I just picked up the game and stated to watch your YT series and when i was looking at this script for myself i noticed that this line can be removed to prevent a error for missing function.

**Comment by chrisrabe** [comment]
Good catch 👍

**Comment by chrisrabe** [comment]
Fixed in pull request #14
