### ISSUE TITLE
Deadlock in Corporation Recruiter Script

### ISSUE THREAD

**Issue by Mac2** [chrisrabe/bitburner-automation#16]
Hi, 

https://github.com/chrisrabe/bitburner-automation/blob/cb85943b46a040f570b1721f6b2d06a325f36220/episodes/ep31/corp-recruiter.js#L98

If you have not enough funds in your corporation the script will enter the while loop, but the business.funds will never be updated.
So you should use directly `corp.getCorporation().funds` instead.

Thanks for all the work and the interesting guidelines!

best,
Mac

**Comment by chrisrabe** [comment]
That's a good catch 👍

**Comment by chrisrabe** [comment]
Implemented in #19
